<?php
/**
 * Created by PhpStorm.
 * User: helena
 * Date: 02.04.2015
 * Time: 18:33
 */

class TopicModel extends SiteModel{


    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->setTable('topic');
    }


} 